name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu
    container: ubuntu:22.04
    steps:
      - name: Install base tools
        run: |
          apt-get update
          apt-get install -y curl wget git sudo ca-certificates

      - name: Checkout
        uses: https://github.com/actions/checkout@v4

      - name: Setup environment
        run: |
          # Install Node.js
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs
          # Install Rust
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          rustc --version
          cargo --version
          node --version
          npm --version

      - name: Install Linux dependencies
        run: |
          apt-get install -y build-essential libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf jq libssl-dev xdg-utils

      - name: Install Windows cross-compile dependencies
        run: |
          apt-get install -y lld llvm clang nsis
          source "$HOME/.cargo/env"
          rustup target add x86_64-pc-windows-msvc
          cargo install --locked cargo-xwin

      - name: Install frontend dependencies
        run: npm ci

      - name: Build Tauri
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: |
          source "$HOME/.cargo/env"
          npx tauri build

      - name: Build Tauri Windows
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: |
          source "$HOME/.cargo/env"
          npx tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc

      - name: Collect release files
        run: |
          mkdir -p release-assets
          cp src-tauri/target/release/bundle/deb/*.deb release-assets/ 2>/dev/null || true
          cp src-tauri/target/release/bundle/deb/*.deb.sig release-assets/ 2>/dev/null || true
          cp src-tauri/target/release/bundle/appimage/*.AppImage release-assets/ 2>/dev/null || true
          cp src-tauri/target/release/bundle/appimage/*.AppImage.sig release-assets/ 2>/dev/null || true
          cp src-tauri/target/release/bundle/rpm/*.rpm release-assets/ 2>/dev/null || true
          cp src-tauri/target/release/bundle/rpm/*.rpm.sig release-assets/ 2>/dev/null || true
          cp src-tauri/target/x86_64-pc-windows-msvc/release/bundle/nsis/*.exe release-assets/ 2>/dev/null || true
          cp src-tauri/target/x86_64-pc-windows-msvc/release/bundle/nsis/*.exe.sig release-assets/ 2>/dev/null || true
          ls -la release-assets/

      - name: Extract changelog
        id: changelog
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          NOTES=$(sed -n "/^## \[${TAG}\]/,/^## /{/^## \[${TAG}\]/d;/^## /d;p}" CHANGELOG.md)
          if [ -z "$NOTES" ]; then
            NOTES=$(sed -n "/^## ${TAG}/,/^## /{/^## ${TAG}/d;/^## /d;p}" CHANGELOG.md)
          fi
          NOTES=$(echo "$NOTES" | sed -e '/./,$!d' -e :a -e '/^\n*$/{$d;N;ba}')
          {
            echo "notes<<CHANGELOG_EOF"
            echo "$NOTES"
            echo "CHANGELOG_EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Generate latest.json
        run: |
          TAG="${GITHUB_REF_NAME}"
          PUB_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          BASE_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/download/${TAG}"

          LINUX_SIG=""
          APPIMAGE_FILE=""
          WINDOWS_SIG=""
          WINDOWS_EXE=""

          for f in release-assets/*.AppImage.sig; do
            [ -f "$f" ] && LINUX_SIG=$(cat "$f")
          done
          for f in release-assets/*.AppImage; do
            [ -f "$f" ] && APPIMAGE_FILE=$(basename "$f")
          done
          for f in release-assets/*-setup.exe.sig; do
            [ -f "$f" ] && WINDOWS_SIG=$(cat "$f")
          done
          for f in release-assets/*-setup.exe; do
            [ -f "$f" ] && WINDOWS_EXE=$(basename "$f")
          done

          PLATFORMS="{}"
          if [ -n "$LINUX_SIG" ] && [ -n "$APPIMAGE_FILE" ]; then
            PLATFORMS=$(echo "$PLATFORMS" | jq \
              --arg sig "$LINUX_SIG" \
              --arg url "${BASE_URL}/${APPIMAGE_FILE}" \
              '. + {"linux-x86_64": {"signature": $sig, "url": $url}}')
          fi
          if [ -n "$WINDOWS_SIG" ] && [ -n "$WINDOWS_EXE" ]; then
            PLATFORMS=$(echo "$PLATFORMS" | jq \
              --arg sig "$WINDOWS_SIG" \
              --arg url "${BASE_URL}/${WINDOWS_EXE}" \
              '. + {"windows-x86_64": {"signature": $sig, "url": $url}}')
          fi

          jq -n \
            --arg version "$TAG" \
            --arg notes "${{ steps.changelog.outputs.notes }}" \
            --arg pub_date "$PUB_DATE" \
            --argjson platforms "$PLATFORMS" \
            '{version: $version, notes: $notes, pub_date: $pub_date, platforms: $platforms}' \
            > release-assets/latest.json

          echo "Generated latest.json:"
          cat release-assets/latest.json

      - name: Create release and upload assets
        env:
          FORGEJO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${GITHUB_REF_NAME}"
          API_URL="${GITHUB_SERVER_URL}/api/v1"
          REPO="${GITHUB_REPOSITORY}"

          BODY=$(cat <<'BODY_EOF'
          ${{ steps.changelog.outputs.notes }}

          ---

          ## Installation

          **Windows** : Téléchargez le fichier `.exe` ci-dessous.
          **Linux** : Téléchargez le fichier `.deb` ou `.AppImage` ci-dessous.
          BODY_EOF
          )

          # Create release
          RELEASE_RESPONSE=$(curl -s -X POST \
            "${API_URL}/repos/${REPO}/releases" \
            -H "Authorization: token ${FORGEJO_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "$(jq -n \
              --arg tag "$TAG" \
              --arg name "Simpl'Résultat ${TAG}" \
              --arg body "$BODY" \
              '{tag_name: $tag, name: $name, body: $body, draft: false, prerelease: false}')")

          RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id')
          echo "Created release ID: $RELEASE_ID"

          if [ "$RELEASE_ID" = "null" ] || [ -z "$RELEASE_ID" ]; then
            echo "ERROR: Failed to create release"
            echo "$RELEASE_RESPONSE"
            exit 1
          fi

          # Upload all assets
          for file in release-assets/*; do
            FILENAME=$(basename "$file")
            ENCODED_FILENAME=$(printf '%s' "$FILENAME" | jq -sRr @uri)
            FILESIZE=$(stat -c%s "$file")
            echo "Uploading: $FILENAME (${FILESIZE} bytes)"
            HTTP_CODE=$(curl -w "%{http_code}" --max-time 300 -X POST \
              "${API_URL}/repos/${REPO}/releases/${RELEASE_ID}/assets?name=${ENCODED_FILENAME}" \
              -H "Authorization: token ${FORGEJO_TOKEN}" \
              -H "Content-Type: application/octet-stream" \
              --data-binary "@${file}" \
              -o /tmp/upload_response.json)
            echo "HTTP $HTTP_CODE"
            if [ "$HTTP_CODE" != "201" ]; then
              echo "Upload failed:"
              cat /tmp/upload_response.json
              echo ""
            fi
          done

          echo "Release created: ${GITHUB_SERVER_URL}/${REPO}/releases/tag/${TAG}"

      - name: Publish latest.json to package registry
        env:
          FORGEJO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          API_URL="${GITHUB_SERVER_URL}/api/packages/${GITHUB_REPOSITORY_OWNER}/generic/simpl-resultat/latest"
          echo "Uploading latest.json to package registry..."
          HTTP_CODE=$(curl -w "%{http_code}" -X PUT \
            "${API_URL}/latest.json" \
            -H "Authorization: token ${FORGEJO_TOKEN}" \
            -H "Content-Type: application/json" \
            --data-binary "@release-assets/latest.json" \
            -o /tmp/pkg_response.json)
          echo "HTTP $HTTP_CODE"
          if [ "$HTTP_CODE" != "201" ] && [ "$HTTP_CODE" != "409" ]; then
            echo "Upload failed:"
            cat /tmp/pkg_response.json
          fi
          if [ "$HTTP_CODE" = "409" ]; then
            echo "Package version exists, deleting and re-uploading..."
            curl -s -X DELETE \
              "${API_URL}/latest.json" \
              -H "Authorization: token ${FORGEJO_TOKEN}"
            HTTP_CODE=$(curl -w "%{http_code}" -X PUT \
              "${API_URL}/latest.json" \
              -H "Authorization: token ${FORGEJO_TOKEN}" \
              -H "Content-Type: application/json" \
              --data-binary "@release-assets/latest.json" \
              -o /tmp/pkg_response.json)
            echo "Re-upload HTTP $HTTP_CODE"
          fi
